Almost fixed. :\
Except functional tests sometimes fail with:

test/functional/rpc_mempool_info.py --timeout-factor=50
2024-09-12T20:44:13.697000Z TestFramework (INFO): PRNG seed is: 4502209873054792873
2024-09-12T20:44:13.698000Z TestFramework (INFO): Initializing test directory /run/user/1001/bitcoin_func_test_e_hj2kw0
2024-09-12T20:44:14.304000Z TestFramework (INFO): Find transactions spending outputs
2024-09-12T20:44:14.307000Z TestFramework (INFO): Find transaction spending multiple outputs
2024-09-12T20:44:14.308000Z TestFramework (INFO): Find no transaction when output is unspent
2024-09-12T20:44:14.311000Z TestFramework (INFO): Mixed spent and unspent outputs
2024-09-12T20:44:14.312000Z TestFramework (INFO): Unknown input fields
2024-09-12T20:44:14.312000Z TestFramework (INFO): Invalid vout provided
2024-09-12T20:44:14.313000Z TestFramework (INFO): Invalid txid provided
2024-09-12T20:44:14.314000Z TestFramework (INFO): Missing outputs
2024-09-12T20:44:14.314000Z TestFramework (INFO): Missing vout
2024-09-12T20:44:14.315000Z TestFramework (INFO): Missing txid
2024-09-12T20:44:14.379000Z TestFramework (INFO): Check that our txospenderindex is updated when a reorg replaces a spending transaction
2024-09-12T20:44:14.517000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/hodlinator/bitcoin/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/home/hodlinator/bitcoin/test/functional/rpc_mempool_info.py", line 144, in run_test
    assert_equal(result, [ {'txid' : confirmed_utxo['txid'], 'vout' : 0, 'spendingtxid' : tx2["txid"]} ])
  File "/home/hodlinator/bitcoin/test/functional/test_framework/util.py", line 75, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not([{'txid': 'fab2396e3f726e1801b9e7303cf294783a3fd7e19ddc8f2dfa55e25b01575b3e', 'vout': 0, 'spendingtxid': '96e6e2d113b64c4ccdea416cd84c57054e04b49b785c2b3adb2131473cbaf814'}] == [{'txid': 'fab2396e3f726e1801b9e7303cf294783a3fd7e19ddc8f2dfa55e25b01575b3e', 'vout': 0, 'spendingtxid': '6a20a4a1d7184174b4ebf8e9d96654fd469c5cec9a9261850e59b3a4c963d368'}])